"use client"
import "./globals.css";
import type { Metadata } from 'next'
import store from '@/store'
import { Provider } from 'react-redux';
import {NextUIProvider} from '@nextui-org/react'

export const metadata: Metadata = {
  title: 'Pokedex App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <Provider store={store}>
            {children}
          </Provider>
        </NextUIProvider>
      </body>
    </html>
  )
}
