"use client"
import "./globals.css";
import type { Metadata } from 'next'
import store from '@/store'
import { Provider } from 'react-redux';
import {NextUIProvider} from '@nextui-org/react'
import type { ReactElement, ReactNode } from 'react';
import type { NextPage } from 'next';
import type { AppProps } from 'next/app'


// export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
//   getLayout?: (page: ReactElement) => ReactNode
// };
// type AppPropsWithLayout = AppProps & {
//   Component: NextPageWithLayout
// };

// export default function App({ Component, pageProps }: AppPropsWithLayout) {
//   const getLayout = Component.getLayout ?? ((page) => page)
//   return getLayout(
//     <NextUIProvider>
//     <Provider store={ store }>
//         <Component {...pageProps} />
//     </Provider>
//     </NextUIProvider>
//   )
// };

export const metadata: Metadata = {
  title: 'Pokedex App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <Provider store={store}>
            {children}
          </Provider>
        </NextUIProvider>
      </body>
    </html>
  )
}
